### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by SzotsGabor** [Sidhant-Roymoulik/Lux#4]
Hi Sidhan,

I am Gabor Szots from the CCRL testing group.

I would just like to suggest to include version numbering in the UCI id. That would make identification easier if in the futere further versions will be released and tested.

BTW, the exe you provide does not work for me but compiling has been successful and that works. FYI, I've got these warnings:

eval.cpp:1:9: warning: #pragma once in main file
    1 | #pragma once
      |         ^~~~
move_score.cpp:1:9: warning: #pragma once in main file
    1 | #pragma once
      |         ^~~~
uci.cpp:1:9: warning: #pragma once in main file
    1 | #pragma once
      |         ^~~~

**Comment by Sidhant-Roymoulik** [comment]
The .exe I provided was the one I used for testing on my local machine. Would you recommend including the binary or should I just have people compile on their local machines?

I also added the other fixes you suggested.

**Comment by SzotsGabor** [comment]
Most users cannot compile for themselves so binaries for various platforms would be required.

FYI, I am testing v2.3 because I did not expect you'd release a new version so soon. Not sure when I'll have time for v3.0 (or a later version if you release one). It depends mostly on how active other authors will be.

**Comment by Sidhant-Roymoulik** [comment]
Thank you for your suggestions and testing. I'll look into creating various binaries for different systems.

You can expect versions coming out quickly for now since I'm still implementing fairly popular features.

**Comment by SzotsGabor** [comment]
As it is early stages in my testing I offer you two options.

1. I stop testing v2.3 and test v3.0 instead. I am going to test future versions as well.
2. I complete testing v2.3 and pick up a version later when circumstances allow.

Which would you like me to do?

EDIT: Time expired, I chose option 2.
