### ISSUE TITLE
Not sure how to contact you regarding a tourney that Lux is in.

### ISSUE THREAD

**Issue by GrahamCCRL** [Sidhant-Roymoulik/Lux#6]
MONSTER IN THE WASTELAND

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2023.cgb book
12 minutes with 8 second increments.
4 cycles 72 rounds
All engines 1CPU (64-bit where available)

Participants

Sirius 5.0.0 64-bit
RookieMonster 1.9.9 64-bit
CM10th Pestilence
Reckless 0.3.0 64-bit
Myrddin 0.90 64-bit
Rengar 1.3.0 64-bit
Raven 1.30 64-bit
Pingu 2.0.0 64-bit
Lux 4.0 64-bit
Luna 2.0.0 64-bit

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your computer, you can watch the games live move by move. You'll also be able to chat to others following the tournament in the chatroom there.
[http://kirill-kryukov.com/chess/discuss ... p?id=42959](http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959)
Host - GrahamCCRL.dyndns.org Port - 16073

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by Sidhant-Roymoulik** [comment]
Hi Graham Banks,
Emailing me works fine if you want to contact me directly. I also check the forum pretty often to see if Lux is playing.

Sidhant

**Comment by GrahamCCRL** [comment]
Okay. I found your email address after I posted in github. :-)

Graham.
