### ISSUE TITLE
Head revision of master returns illegal move infrequently

### ISSUE THREAD

**Issue by cjbolt** [Sidhant-Roymoulik/Lux#7]
Hi,

I have been testing your engine against mine, I built it from source for a Raspberry Pi Zero 2 (arm7 cpu). No issues at all, but I discovered that infrequently it loses due to sending an illegal move (a1a1). I'm guessing your search terminated without backing up a legal move and this is your null move value.

Anyway, I though the information might be helpful to you. In 3705 games played, it lost 10 in this fashion, so fairly low rate, but should be reproducible. I was playing at 2+1 time control. I can give you the PGNs, if you think it would help debug. Probably not, as I expect it is based on timing, not the root position.

Anyhow, good luck with that ;)

Chris

**Comment by Sidhant-Roymoulik** [comment]
Hi Chris,
I’m currently away from my workstation but I have a feeling that the issue has something to do with very low time left at the end of a long game.
If you could share the PGNs that would be great.

Sidhant

**Comment by cjbolt** [comment]
Here are the PGNs, I ran it for a bit longer, rate is now 11 in 4797 games. This is on a system with very little memory so it isn't a very usual test. I haven't seen any failures on my Raspberry Pi 4B, in like 2000 games there, at a longer time control (12:0+8).

[Lux_illegal_moves.zip](https://github.com/Sidhant-Roymoulik/Lux/files/13835350/Lux_illegal_moves.zip)

Still It might be interesting to look into. BTW I was using cutechess to run the tournament: with command line

./cutechess-cli -engine conf="Eubos_Dev" option.Hash=16 -engine conf="Lux_4" option.Hash=16 -each restart=on tc=2:0+1 -concurrency 2 -resign movecount=5 score=600 twosided=true -maxmoves 125 -event vs_lux -games 2 -rounds 6000 -outcomeinterval 10 -openings file=Titus2_4.pgn format=pgn order=sequential -repeat -pgnout ../../Piz2_1_Tourney.pgn -site Piz2_1
